### ISSUE TITLE
Errors in username formatting not caught during dry run

### ISSUE THREAD

**Issue by jaraco** [jeffwidman/bitbucket_issue_migration#20]
In #19, I encountered an error, but only when I tried to run the migration for real. When I ran it using `--dry-run`, the error was not encountered. Dry run should probably catch errors in formatting.

**Comment by TurkeyMan** [comment]
It really should!
It's impossible to DELETE bugs from GH >_< .. you can only 'close' them...

**Comment by serviceman** [comment]
@TurkeyMan the problem with -f comes from Bitbucket's api that are broken, neither "start" nor "limit" work according to [the docs](https://confluence.atlassian.com/bitbucket/issues-resource-296095191.html#issuesResource-GETalistofissuesinarepository'stracker). With 17 issues, if I pass -f 15 it copies the first 2 (=17-15) issues. Similarly, limit does not limit anything but it just takes the last X issues

**Comment by jeffwidman** [comment]
@jaraco did #25 fix this? If not, do you mind submitting your fix as a PR?

**Comment by jaraco** [comment]
@jeffwidman: I don't believe it did. The behavior of formatting a comment is still not captured in the dry run.

**Comment by jeffwidman** [comment]
Thanks!
