### ISSUE TITLE
Gihub organization repository not accessible

### ISSUE THREAD

**Issue by 130s** [jeffwidman/bitbucket_issue_migration#21]
In [README.md](https://github.com/vbabiy/bitbucket_issue_migration/blob/efe981c624f040dd7c7f618185fc5582b87d9902/README.md) (and in https://github.com/vbabiy/bitbucket_issue_migration/pull/14) 

```Note: if you need to migrate to a GitHub organizational repository, use your personal username, but the appropriate API token for the repository.```

AFAIK, [API token is gone from Github](http://stackoverflow.com/a/10418853/577001) and thus I'm not sure how to upload to my organizational repo.

**Comment by pelegm** [comment]
I agree that this seems impossible at the moment.

**Comment by jeffwidman** [comment]
There's an updated patch here: https://github.com/jeffwidman/bitbucket_issue_migration/pull/25#issuecomment-127050756

Before merging, I just need confirmation it doesn't break pushing to an individual-owned repo.
