### ISSUE TITLE
Example usage needs updating

### ISSUE THREAD

**Issue by Narthur** [jeffwidman/bitbucket_issue_migration#26]
According to the script's help command, the script's example usage here on GitHub is outdated.

Script help command output:

    usage: migrate.py [-h] [-n] [-f START]
                      bitbucket_username bitbucket_repo github_username
                      github_repo

    A tool to migrate issues from Bitbucket to GitHub. note: the Bitbucket
    repository and issue tracker have to bepublic

    positional arguments:
      bitbucket_username    Your Bitbucket username
      bitbucket_repo        Bitbucket repository to pull data from.
      github_username       Your GitHub username
      github_repo           GitHub to add issues to. Format: <username>/<repo
                            name>
    
    optional arguments:
      -h, --help            show this help message and exit
      -n, --dry-run         Perform a dry run and print eveything.
      -f START, --start_id START
                            Bitbucket issue id from which to start import

**Comment by henhouse** [comment]
Having same issue.

**Comment by jeffwidman** [comment]
I think this was fixed by #14 - if not, let me know.
