### ISSUE TITLE
GitHub abuse detection block

### ISSUE THREAD

**Issue by henhouse** [jeffwidman/bitbucket_issue_migration#27]
>You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.

Anyone know how sensitive GitHub's thing is?

**Comment by serviceman** [comment]
Running into the same problem (probably), I get a 403 error after the first 10 issues or so.

Maybe a pause in the script can help?

**Comment by ingomueller-net** [comment]
I added a sleep of 10 seconds after pushing a comment. This allowed me to fly under the radar, but maybe it's not a great solution for larger projects...

**Comment by serviceman** [comment]
@ingomueller-net did you push the code somewhere? I'd like to use it for some personal project too, now that I think of it

**Comment by jeffwidman** [comment]
Fixed by switching to using the Github import API directly in ac123bcc36fc50eab130b322df426c32999b318a - thanks to @nicoddemus for the PR.
