### ISSUE TITLE
Update readme that bitbucket labels are supported

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/bitbucket_issue_migration#29]
#25 added support for bitbucket labels/metadata/component and translates them to github labels:
https://github.com/jeffwidman/bitbucket_issue_migration/blob/master/migrate.py#L295

@nicoddemus do you remember what bitbucket metadata & component types refer to?

**Comment by nicoddemus** [comment]
Hi @jeffwidman!

IIRC my patch mapped `kind` and `component` to GH labels... does that answer your question? :smile:

**Comment by jeffwidman** [comment]
Yep thx
