### ISSUE TITLE
System fails with Github 2FA

### ISSUE THREAD

**Issue by mlissner** [jeffwidman/bitbucket_issue_migration#9]
If you have two factor auth turns on in your github account, the uploader fails and throws a 401 error. It would be useful to catch this error and suggest that the person disable 2FA if possible, or that they try their password again.

**Comment by jeffwidman** [comment]
#25 switched from using PyGithub3 to using the new Github import API. I haven't tried it with two-factor, but possibly the new API provides a more specific error message? 

Could you try it and see if this issue is still relevant?
